feat(timeseries-chart): time-series chart axis realignment (#551)
cognitedata/gearbox.js pull request #635
Opened 2020-03-17 13:11 UTC by amevck

changes cherrypicked from the next branch.

2020-03-17 13:19 UTC, cognite-cicd commented
This PR's storybook can now be previewed at the following URL: https://pr-635.gearboxjs.preview.cogniteapp.com

2020-03-17 17:10 UTC, mrtraser requested changes

2020-03-17 17:10 UTC, mrtraser commented on src/components/TimeseriesChart/interfaces.ts
> +  ySubDomains?: { [key: number]: [number, number] };
`key` here is `timeseriesId`, am I right? If yes, it's better to have `timeseriesId` instead of `key`

2020-03-17 17:10 UTC, mrtraser commented on src/components/TimeseriesChart/stories/basic.story.mdx
> +const seriesWithCustomYdomain = [
can we add here exact same structure that we're importing for story example (`yAxisDisplayMode: AxisDisplayMode.ALL` is missed)

2020-03-18 03:31 UTC, cognite-cicd commented
This PR's storybook can now be previewed at the following URL: https://pr-635.gearboxjs.preview.cogniteapp.com

2020-03-18 15:39 UTC, mrtraser approved these changes
LGTM

2020-03-19 08:48 UTC, polomani requested changes
ignore this

2020-03-19 09:49 UTC, polomani approved these changes

2020-03-19 15:59 UTC, hernil approved these changes
These changes seem fine :-) 

Any reason why these are cherry picked instead of releasing next as a whole? There are other minor things we hope might be fixed in next for example by the Griff version bump. Is there an ETA for releasing those?

2020-03-20 03:10 UTC, man-csl commented
> These changes seem fine :-)
> 
> Any reason why these are cherry picked instead of releasing next as a whole? There are other minor things we hope might be fixed in next for example by the Griff version bump. Is there an ETA for releasing those?

Yes upgrade of griff fixed atleast one more but seems like the version that is upgraded to is just a release candidate and there are some instabilities/issues. therefore we had to cherry pick this change without merging the next branch. @hhenriques knows specifics about issues in the griff.

2020-03-20 07:47 UTC, hhenriques commented
@man-csl is spot on. The version of Griff is just an RC and has some instability issues with Timeseries. Was there anything in the next branch that you needed in specific @hernil ?

2020-03-20 09:13 UTC, hernil commented
> @man-csl is spot on. The version of Griff is just an RC and has some instability issues with Timeseries. Was there anything in the next branch that you needed in specific @hernil ?
I made an actual issue describing the problem :-) #637 

Griff 0.5.0 has been in RC for over a year and 78 releases. Any ETA for a stable version?

2020-03-23 08:03 UTC, polomani commented
I am releasing this, so we don't get stuck while deciding on other changes

2020-03-23 08:05 UTC, merged

2020-03-23 08:16 UTC, cognite-cicd commented
:tada: This PR is included in version 1.15.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@cognite/gearbox/v/1.15.0)
- [GitHub release](https://github.com/cognitedata/gearbox.js/releases/tag/v1.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-03-23 08:34 UTC, hhenriques commented
> > @man-csl is spot on. The version of Griff is just an RC and has some instability issues with Timeseries. Was there anything in the next branch that you needed in specific @hernil ?
> 
> I made an actual issue describing the problem :-) #637
> 
> Griff 0.5.0 has been in RC for over a year and 78 releases. Any ETA for a stable version?

There isn't an ETA @hernil. We plan on making changes to the API and don't want to make a GA version which will prevent us from making breaking changes.

We ran into some instability on the next branch which may be due to the Griff bump. We'd need to invest in investigating the issue and may be forced to move away from Griff. However, Gearbox isn't a priority right now so we can't commit to anything.